require 'pry'
require 'rspec/core/formatters/base_formatter'
require_relative 'formatters/custom_formatter'
require_relative 'support/db_helper'
require_relative 'support/redisgraph_helper'
require 'json'
