source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'rails', '~> 6.0.3', '>= 6.0.3.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors', '~> 1.1'

# app gems
gem 'redis', '~> 4.2'
gem 'fast_jsonapi', '~> 1.5'
gem 'sidekiq', '~> 6.1'
gem 'sidekiq-cron', '~> 1.2'
gem 'recursive-open-struct', '~> 1.1'
gem 'pundit', '~> 2.1'
gem 'bcrypt', '~> 3.1'
gem 'omniauth', '~> 1.9'
gem 'omniauth-google-oauth2', '~> 0.8.0'
gem 'omniauth-github', '~> 1.4'
gem 'rolify', '~> 5.3'
gem 'lograge', '~> 0.11.2'
gem 'addressable', '~> 2.7'
gem 'json_schemer', '~> 0.2.15'
gem 'redisgraph', '~> 2.0'
gem 'rspec', '~> 3.9'

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # app gems
  gem 'solargraph', '~> 0.39.15'
  gem 'rubocop', '~> 0.90.0'
  gem 'pry', '~> 0.13.1'
  gem 'better_errors', '~> 2.7'
  gem 'binding_of_caller', '~> 0.8.0'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # app gems
  gem 'rspec-rails', '~> 4.0'
  gem 'factory_bot_rails', '~> 6.1'
end
