source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

gem 'rails', '~> 6.1.3', '>= 6.1.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors', '~> 1.1'

# app gems
gem 'listen', '~> 3.2'
gem 'redis', '~> 4.2'
gem 'redisgraph', '~> 2.0'
gem 'sidekiq', '~> 6.1'
gem 'sidekiq-cron', '~> 1.2'
gem 'parallel', '~> 1.20'
gem 'fast_jsonapi', '~> 1.5'
gem 'recursive-open-struct', '~> 1.1'
gem 'pundit', '~> 2.1'
gem 'bcrypt', '~> 3.1'
gem 'omniauth', '~> 2.0', '>= 2.0.0'
gem 'omniauth-google-oauth2', '~> 0.8.0'
gem 'omniauth-github', '~> 2.0', '>= 2.0.0'
gem 'google-cloud-storage', '~> 1.29'
gem 'rolify', '~> 5.3'
gem 'lograge', '~> 0.11.2'
gem 'rspec', '~> 3.9'
gem 'addressable', '~> 2.7'
gem 'json_schemer', '~> 0.2.15'
gem 'fast_jsonparser', '~> 0.5'
gem 'pry', '~> 0.13.1'
gem 'kramdown', '~> 2.3.1' # update for CVE-2021-28834

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # app gems
  gem 'awesome_print', '~> 1.8'
  gem 'solargraph', '~> 0.40.0'
  gem 'better_errors', '~> 2.7'
  gem 'rubocop', '~> 0.90.0'
  gem 'binding_of_caller', '~> 0.8.0'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # app gems
  gem 'debase', '~> 0.2.4'
  gem 'factory_bot_rails', '~> 6.1', '>= 6.1.0'
  gem 'rspec-rails', '~> 4.0', '>= 4.0.1'
  gem 'ruby-debug-ide', '~> 0.7.2'
end
